#!/bin/bash

set -ex

dist=$1
build_command="${@:2}"

image=achaphiv/ppa-builder:$dist
docker build -t $image -f ../docker-builder/Dockerfile-$dist ../docker-builder
docker run \
  --rm \
  -it \
  -v ~/.gnupg:/home/builder/.gnupg \
  -v $PWD:/files \
  -e "DEBFULLNAME=$DEBFULLNAME" \
  -e "DEBEMAIL=$DEBEMAIL" \
  --userns host \
  -u $(id -u):$(id -g) \
  -w /files \
  $image \
  sh -c "$build_command"
