#!/bin/sh

set -ex

build_openjdk_7() {
  local dist=$1
  local dist_packaging=$2
  local version=$3
  local ppa_version=$4
  ../docker-builder/run $dist ./get-source openjdk-7 $version
  ../docker-builder/run $dist_packaging ./build-package openjdk-7 $version $dist $ppa_version enable_infinality.patch

  git tag ${dist}-openjdk-7-${version}${ppa_version}
}

build_openjdk_8() {
  local dist=$1
  local dist_packaging=$2
  local version=$3
  local ppa_version=$4
  ../docker-builder/run $dist ./get-source openjdk-8 $version
  ../docker-builder/run $dist_packaging ./build-package openjdk-8 $version $dist $ppa_version enable_tuxjdk.patch

  git tag ${dist}-openjdk-8-${version}${ppa_version}
}

#build_openjdk_7 trusty trusty 7u171-2.6.13-0ubuntu0.14.04.2 ppa1
#build_openjdk_8 artful yakkety 8u171-b11-0ubuntu0.17.10.1 ppa1
#build_openjdk_8 zesty yakkety 8u151-b12-0ubuntu0.17.04.2 ppa1
build_openjdk_8 xenial xenial 8u171-b11-0ubuntu0.16.04.1 ppa1
