#!/bin/bash

set -exo pipefail

package=$1
version=$2
dist=$3
ppa_version=$4
patchfile=$5

starting_dir=$PWD

build_dir=build-${package}-${dist}
cd ${build_dir}

cd ${package}*/

cp ${starting_dir}/tuxjdk/quilt-patches/tuxjdk/add-fontconfig-support.diff debian/patches/

patch -p1 < ${starting_dir}/${patchfile}

changelog=$(mktemp)

cat <<-EOF > ${changelog}
${package} (${version}${ppa_version}) ${dist}; urgency=low

  * Turn on --enable-infinality flag

 -- ${DEBFULLNAME} <${DEBEMAIL}>  $(date -R)

EOF

cat debian/changelog >> ${changelog}

mv ${changelog} debian/changelog

debuild -S -sd -pgpg2

ps ax | grep gpg-agent | grep -v grep | awk '{print $1}' | xargs kill || true

cd ../

dput -c ${starting_dir}/dput.cf openjdk-fontfix *changes
