FROM ubuntu:16.04 

RUN sed -i -e 's/# deb-src/deb-src/g' /etc/apt/sources.list

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y dpkg-dev devscripts debhelper

RUN useradd -ms /bin/bash builder

USER builder
WORKDIR /home/builder
