#!/bin/bash

set -ex

build_freetype() {
  local dist=$1
  local dist_packaging=$2
  local source_version=$3
  local ppa_version=$4

  local version=2.9.1
  local full_version=${version}-0ubuntu0${ppa_version}

  ../docker-builder/run $dist ./get-source-freetype $source_version
  ../docker-builder/run $dist_packaging ./build-freetype $dist $version $full_version

  git tag ${dist}-freetype-${full_version}
}

#build_freetype trusty 2.5.2-1ubuntu2.5 'infinality-2.5.3.patch' 'ppa1bohoomileb5a6af0e99ec0d1c25521b6f8196106508c9360'
#build_freetype utopic 2.5.2-2ubuntu1.1 'infinality-2.5.3.patch' 'ppa1bohoomileb5a6af0e99ec0d1c25521b6f8196106508c9360'
#build_freetype vivid 2.5.2-2ubuntu3.1 'infinality-2.5.3.patch' 'ppa1bohoomileb5a6af0e99ec0d1c25521b6f8196106508c9360'
#build_freetype wily 2.5.2-4ubuntu2 'infinality-2.5.3.patch' 'ppa1bohoomileb5a6af0e99ec0d1c25521b6f8196106508c9360'
#build xenial ./build-freetype 2.6.1-0.1ubuntu2 'enable-subpixel-hinting.patch' 'ppa8'
#build_fontconfig xenial 2.11.94-0ubuntu1 ppa1

#../docker-builder/run trusty ./build-freetype-2.5.2 2.5.2-1ubuntu2.8 'ppa1'

#../docker-builder/run xenial ./build-cairo 1.14.6-1 ubuntu0ppa1
#../docker-builder/run xenial ./build-freetype 2.6.1-0.1ubuntu2 '.16.04.2ppa4'

#../docker-builder/run yakkety ./build-cairo 1.14.6-1build1 ubuntu0ppa1
#../docker-builder/run yakkety ./build-freetype 2.6.3-3ubuntu1 '.16.10.2ppa1'

#../docker-builder/run zesty ./build-cairo 1.14.8-1 ubuntu0ppa1
#build_freetype zesty yakkety 2.6.3-3ubuntu2 '.17.04ppa2'

#build_freetype artful yakkety 2.8-0.2ubuntu2 '.17.10ppa1'

#build_freetype bionic yakkety 2.8.1-2ubuntu2 '.18.04ppa3'
#../docker-builder/run bionic ./build-cairo 1.15.10-2 '.18.04ppa1'

#build_freetype cosmic cosmic 2.8.1-2ubuntu2 '.18.10ppa1'
../docker-builder/run cosmic ./build-cairo 1.15.12-1 '.18.10ppa1'
