#!/bin/bash

#build_freetype trusty 2.5.2-1ubuntu2.5 'infinality-2.5.3.patch' 'ppa1bohoomileb5a6af0e99ec0d1c25521b6f8196106508c9360'
#build_freetype utopic 2.5.2-2ubuntu1.1 'infinality-2.5.3.patch' 'ppa1bohoomileb5a6af0e99ec0d1c25521b6f8196106508c9360'
#build_freetype vivid 2.5.2-2ubuntu3.1 'infinality-2.5.3.patch' 'ppa1bohoomileb5a6af0e99ec0d1c25521b6f8196106508c9360'
#build_freetype wily 2.5.2-4ubuntu2 'infinality-2.5.3.patch' 'ppa1bohoomileb5a6af0e99ec0d1c25521b6f8196106508c9360'
#build xenial ./build-freetype 2.6.1-0.1ubuntu2 'enable-subpixel-hinting.patch' 'ppa8'
#build_fontconfig xenial 2.11.94-0ubuntu1 ppa1

#../docker-builder/run xenial ./build-cairo 1.14.6-1 ubuntu0ppa1
../docker-builder/run xenial ./build-freetype 2.6.1-0.1ubuntu2 'ppa2'
