#!/bin/bash

set -ex

starting_dir=$(pwd)

version=$1
ppa_version=$2

package='freetype'
dist=$(lsb_release -s -c)
new_version=2.6.5-0ubuntu0${ppa_version}

build_dir=build-${package}-${dist}
rm -rf ${build_dir}
mkdir ${build_dir}
cd ${build_dir}

apt-get source ${package}=${version}

# Remove old packages
rm *.orig.tar.gz
rm *.diff.gz
rm *.dsc

rm ${package}*/*.tar.bz2

mv ${package}* ${package}-2.6.5/
wget https://launchpad.net/~no1wantdthisname/+archive/ubuntu/ppa/+files/freetype_2.6.5.orig.tar.gz
tar xvzfp freetype_2.6.5.orig.tar.gz

cd ${package}*/

# ignore compiler warnings
sed -i -e '/export DEB_CFLAGS_MAINT_APPEND := -Werror/d' debian/rules

cp ${starting_dir}/infinality_bundle/01_freetype2-iu/0002-infinality-2.6.5-2016.08.18.patch debian/patches-freetype/
echo 0002-infinality-2.6.5-2016.08.18.patch >> debian/patches-freetype/series

# Redundant
sed -i -e '/enable-subpixel-rendering.patch/d' debian/patches-freetype/series

# remove since 2.6.5 changes things
sed -i -e '/0001-Revert-pcf-Signedness-fixes.patch/d' debian/patches-freetype/series
sed -i -e '/compiler_hardening_fixes.patch/d' debian/patches-ft2demos/series

# Level | Failure
# 0     | impossible (all checks disabled)
# 1     | symbols have disappeared
# 2     | symbols have been introduced
# 3     | libraries have disappeared
# 4     | libraries have been introduced
sed -i -e 's/DPKG_GENSYMBOLS_CHECK_LEVEL = 4/DPKG_GENSYMBOLS_CHECK_LEVEL = 0/' debian/rules

CHANGELOG=$(mktemp)

cat <<-EOF > ${CHANGELOG}
${package} (${new_version}) ${dist}; urgency=low

  * Ignore compiler warnings
  * Update freetype to 2.6.5
  * Remove unnecessary patches
  * Add infinality patch
  * Ignore extra symbols

 -- ${DEBFULLNAME} <${DEBEMAIL}>  $(date -R)

EOF

cat debian/changelog >> ${CHANGELOG}

mv ${CHANGELOG} debian/changelog

debuild -S -sd

cd ../

dput -c ${starting_dir}/dput.cf ppa *changes

cd ${starting_dir}
