#!/bin/bash

set -ex

build_freetype() {
  local dist=$1
  local dist_packaging=$2
  local source_version=$3
  local ppa_version=$4

  local version=2.9.1
  local full_version=${version}-0ubuntu0${ppa_version}

  ../docker-builder/run $dist ./get-source-freetype $source_version
  ../docker-builder/run $dist_packaging ./build-freetype $dist $version $full_version

  git tag ${dist}-freetype-${full_version}
}

build_freetype_2_9_1() {
  local dist=$1
  local dist_packaging=$2
  local source_version=$3
  local ppa_version=$4

  local version=2.9.1
  local full_version=${source_version}${ppa_version}

  ../docker-builder/run $dist ./get-source-freetype $source_version
  ../docker-builder/run $dist_packaging ./build-freetype-2.9.1 $dist $version $full_version

  git tag ${dist}-freetype-${full_version}
}

build_cairo() {
  local dist=$1
  local source_version=$2
  local ppa_version=$3

  local full_version=${source_version}${ppa_version}

  ../docker-builder/run $dist ./build-cairo $source_version $ppa_version

  git tag ${dist}-freetype-${full_version}
}

#build_freetype zesty yakkety 2.6.3-3ubuntu2 '.17.04ppa2'

#build_freetype artful yakkety 2.8-0.2ubuntu2 '.17.10ppa1'

#build_freetype bionic yakkety 2.8.1-2ubuntu2 '.18.04ppa3'
#../docker-builder/run bionic ./build-cairo 1.15.10-2 '.18.04ppa1'

#build_freetype cosmic cosmic 2.8.1-2ubuntu2 '.18.10ppa1'
#../docker-builder/run cosmic ./build-cairo 1.15.12-1 '.18.10ppa1'

build_freetype_2_9_1 disco disco 2.9.1-3 'ubuntu0.19.04ppa1'
