#!/bin/bash

set -ex

version=$1
ppa_version=$2

package=freetype
dist=$(lsb_release -s -c)

updated_version=2.7.1
new_version=${updated_version}-0ubuntu0${ppa_version}

starting_dir=$(pwd)
build_dir=${starting_dir}/build-${package}-${dist}
working_dir=${build_dir}/${package}-${updated_version}

main() {
  remove_old_build
  create_working_dir
  fix_patches
  ignore_issues
  update_changelog
  generate_package_from_ppa_archive || generate_package_from_official_archive
  upload_package_to_ppa
  cd ${starting_dir}
}

remove_old_build() {
  rm -rf ${build_dir}
  mkdir ${build_dir}
}

create_working_dir() {
  cd ${build_dir}
  apt-get source ${package}=${version}

  # Remove old packages
  rm *.orig.tar.gz
  rm *.diff.gz
  rm *.dsc
  rm ${package}*/*.tar.bz2

  mv ${package}* ${package}-${updated_version}/
}

fix_patches() {
  cd ${working_dir}

  add_patch() {
    local patch_name=$1
    cp ${starting_dir}/infinality_bundle/01_freetype2-iu/$patch_name debian/patches-freetype/
    echo $patch_name >> debian/patches-freetype/series
  }

  add_patch 0001-Enable-table-validation-modules.patch
  add_patch 0002-infinality-2.7.1-2017.01.11.patch

  # Resolve conflict caused by infinality
  sed -i -e '/freetype-2.1.7-backwards.compat.patch -p0/d' debian/patches-freetype/series
  echo "freetype-2.1.7-backwards.compat.patch -F3 -p0" >> debian/patches-freetype/series

  # Redundant
  sed -i -e '/enable-subpixel-rendering.patch/d' debian/patches-freetype/series
  sed -i -e '/enable-gxvalid-otvalid.patch/d' debian/patches-freetype/series

  # remove since updated version changes things
  sed -i -e '/0001-Revert-pcf-Signedness-fixes.patch/d' debian/patches-freetype/series
  sed -i -e '/revert_scalable_fonts_metric.patch/d' debian/patches-freetype/series
  sed -i -e '/CVE-2014-2240.patch/d' debian/patches-freetype/series
  sed -i -e '/compiler_hardening_fixes.patch/d' debian/patches-ft2demos/series
}

ignore_issues() {
  cd ${working_dir}
  # ignore compiler warnings
  sed -i -e '/export DEB_CFLAGS_MAINT_APPEND := -Werror/d' debian/rules
  # Level | Failure
  # 0     | impossible (all checks disabled)
  # 1     | symbols have disappeared
  # 2     | symbols have been introduced
  # 3     | libraries have disappeared
  # 4     | libraries have been introduced
  sed -i -e 's/DPKG_GENSYMBOLS_CHECK_LEVEL = 4/DPKG_GENSYMBOLS_CHECK_LEVEL = 0/' debian/rules
}

update_changelog() {
  cd ${working_dir}
  changelog=$(mktemp)

  cat <<EOF | sed 's/^  //' > ${changelog}
  ${package} (${new_version}) ${dist}; urgency=low

    * Ignore compiler warnings
    * Update freetype to ${updated_version}
    * Remove unnecessary patches
    * Add infinality patch
    * Ignore extra symbols

   -- ${DEBFULLNAME} <${DEBEMAIL}>  $(date -R)

EOF
  cat debian/changelog >> ${changelog}
  mv ${changelog} debian/changelog
}

generate_package_from_ppa_archive() {
  cd ${build_dir}
  wget https://launchpad.net/~no1wantdthisname/+archive/ubuntu/ppa/+files/freetype_${updated_version}.orig.tar.gz || return 1
  tar xvzfp freetype_${updated_version}.orig.tar.gz
  cd ${working_dir}
  debuild -S -sd -pgpg2
}

generate_package_from_official_archive() {
  cd ${working_dir}
  gpg --recv-keys E707FDA5
  ./debian/rules get-orig-source
  tar xvzfp *.orig.tar.gz --strip-components=1
  mv *.orig.tar.gz ..
  debuild -S -sa -pgpg2
}

upload_package_to_ppa() {
  dput -c ${starting_dir}/dput.cf ppa ${build_dir}/*changes
}

main

